// ==UserScript==
// @name        Archer's Steam Combine
// @namespace   Steam_Combine
// @description bunch of tools for OVH, SG, steam store
// @include	    /^https?\:\/\/.+/
// @version     1.3
// @grant       none
// @run-at      document-idle
// @author		Archer-Dante
// ==/UserScript==

if((location.href).indexOf("steamkeys.ovh")>0){console.log("Открыт подходящий URL: "+location.href);var temp_rate=30,temp_kSell=117,temp_kPrice=149,temp_accs=1,deals_info=$('#DataTables_Table_0_info').html(),deals_text='of ',deals_pos1=deals_info.indexOf(deals_text)+deals_text.length,deals_pos2=deals_info.indexOf(' ',deals_pos1)-deals_pos1,deals_left=deals_info.substr(deals_pos1,deals_pos2);$('#buttons center').append('<div class="btn" id="hks" style="background:#c45">Изменить рассчёт<br><i><span style="font-size:0.7em">(Archer-Dante ver.)</span></i></div>');$('#buttons center').append('<div class="btn" id="hks_forms" style="background:#9B2B3A;width:130px;font-size:0.9em">Рейт продажи сета<br><input id="sets_rate" type="text" data-user="QE5vZGVucw==" size="14" placeholder="Рейт продажи сета" value="'+temp_rate+'"></div>')
$('#buttons center').append('<div class="btn" id="hks_forms" style="background:#9B2B3A;width:130px;font-size:0.9em">Цена продажи ключа<br><input id="sell_key_price" type="text" size="14" placeholder="Цена продажи ключа" value="'+temp_kSell+'"></div>')
$('#buttons center').append('<div class="btn" id="hks_forms" style="background:#9B2B3A;width:130px;font-size:0.9em">Цена ключа в CS:GO<br><input id="key_price_orignal" type="text" size="14" placeholder="число" value="'+temp_kPrice+'"></div>');$('#buttons center').append('<div class="btn" id="hks_forms" style="background:#9B2B3A;width:130px;font-size:0.9em">Сколько строк?<br><input id="calc_deals" type="text" size="14" placeholder="Сколько строк?" value="'+deals_left+'"></div>');if($("th.sorting:nth-child(3)").html()!='Надо'){console.log("Тип авторизации: Стандартный");var account=0;$('#buttons center').append('<div class="btn" id="hks_forms" style="background:#9B2B3A;width:130px;font-size:0.9em">Сколько аккаунтов?<br><input id="total_accs" type="text" size="14" placeholder="Сколько аккаунтов?" value="'+temp_accs+'"></div>');$("th.sorting:nth-child(2)").after('<th title="Количество ключей для фермы" style="width: 0px;font-size:0.1em" class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Надо: activate to sort column ascending">Надо</th>');for(i=1;i<deals_left;i++){$('tbody > tr:nth-child('+i+') > td:nth-child(2)').after('<td><center><b></b></center></td>');}}else{console.log("Тип авторизации: Через FLH");var account=1;$('#buttons center').append('<div class="btn" id="hks_forms" style="background:#9B2B3A;width:130px;font-size:0.9em;"><b>Аккаунт:</b><br>Премиум</div>');}
$('#top').remove();$('#DataTables_Table_0').width(1250);$('#DataTables_Table_1').width(1250);$('#DataTables_Table_2').width(1250);var nice_width=200;$('th.sorting_asc').width(nice_width-75);$('th.sorting:nth-child(5)').width(nice_width-75);$('th.sorting:nth-child(6)').width(nice_width-75);$('th.sorting:nth-child(7)').width(nice_width+150);$('th.sorting:nth-child(8)').width(nice_width+150);$('th.sorting:nth-child(9)').width(nice_width+100);$('th.sorting:nth-child(10)').width(nice_width+100);$('#hks').click(function(){var sell_key_price=$('#sell_key_price').val(),std_key_price=$('#key_price_orignal').val(),part_of_cake=87,sets_rate=$('#sets_rate').val(),calc_deals=$('#calc_deals').val(),steam_to_qiwi=Math.round(sell_key_price/std_key_price*100);for(var i=1;i<calc_deals;i++){if(account==0){var bot=$('#total_accs').val();}
else{var bot=$('tbody > tr:nth-child('+i+') > td:nth-child(3) b center').html();}
var price=$('tbody > tr:nth-child('+i+') > td:nth-child(4) a').html(),cost=(bot*price).toFixed(2),title=$('tbody > tr:nth-child('+i+') > td:nth-child(7)').attr('title'),worst_text='Худший прогноз: ',worst_pos1=title.indexOf(worst_text)+worst_text.length,worst_pos2=title.indexOf(' ',worst_pos1)-worst_pos1,worst_val=Number(title.substr(worst_pos1,worst_pos2)),spread_text='Разброс цен: ',spread_pos1=title.indexOf(spread_text)+spread_text.length,spread_pos2=title.indexOf(' ',spread_pos1)-spread_pos1,spread_val=Number(title.substr(spread_pos1,spread_pos2)),set_text='Цена сета: ',set_pos1=title.indexOf(set_text)+set_text.length,set_pos2=title.length,set_val=Number(title.substr(set_pos1,set_pos2));if(worst_val>99999){worst_val=0}
if(set_val>99999){set_val=0}
var set_size=$('tbody:not(:nth-child(1)) > tr:nth-child('+i+') > td:nth-child(1) a').html(),min_money_from_MARKET=((Math.ceil(set_size/2)*bot*(set_val/set_size))/100*part_of_cake/100*steam_to_qiwi-cost).toFixed(2),set_value_for_qiwi_MARKET=(set_val/100*part_of_cake/100*steam_to_qiwi).toFixed(2),min_money_from_SETSELL=(Math.ceil(set_size/2)*bot/set_size/sets_rate*sell_key_price-cost).toFixed(2),set_value_for_qiwi_SETSELL=(sell_key_price/sets_rate).toFixed(2);$('tbody > tr:nth-child('+i+') > td:nth-child(6)').html("<center>"+cost+" р.</center>");if(Number(set_value_for_qiwi_MARKET)>Number(set_value_for_qiwi_SETSELL)){$('tbody > tr:nth-child('+i+') > td:nth-child(7)').html("<center><span style='color:#000'><b>"+set_value_for_qiwi_MARKET+" р.</b></span></center>");$('tbody > tr:nth-child('+i+') > td:nth-child(8)').html("<center><span style='color:#bbb'>"+set_value_for_qiwi_SETSELL+" р.</span></center>");}else{$('tbody > tr:nth-child('+i+') > td:nth-child(7)').html("<center><span style='color:#bbb'>"+set_value_for_qiwi_MARKET+"  р.</span></center>");$('tbody > tr:nth-child('+i+') > td:nth-child(8)').html("<center><span style='color:#000'><b>"+set_value_for_qiwi_SETSELL+" р.</b></span></center>");}
if(Number(min_money_from_MARKET)>Number(min_money_from_SETSELL)){$('tbody > tr:nth-child('+i+') > td:nth-child(9)').html("<center><b>"+min_money_from_MARKET+" р.</b></center>");$('tbody > tr:nth-child('+i+') > td:nth-child(10)').html("<center><span style='color:#bbb'>"+min_money_from_SETSELL+" р.</span></center>");}else{$('tbody > tr:nth-child('+i+') > td:nth-child(9)').html("<center><span style='color:#bbb'>"+min_money_from_MARKET+" р.</span></center>");$('tbody > tr:nth-child('+i+') > td:nth-child(10)').html("<center><b>"+min_money_from_SETSELL+" р.</b></center>");}}
$('th.sorting_asc').html('Shop #1');$('th.sorting:nth-child(5)').html('Shop #2');$('th.sorting:nth-child(6)').html('Расходы<br><i>(на всех)</i>');$('th.sorting:nth-child(7)').html('Цена сета<br>через Market');$('th.sorting:nth-child(8)').html('Цена сета<br>через Trade');$('th.sorting:nth-child(9)').html('Прибыль<br>через Market');$('th.sorting:nth-child(10)').html('Прибыль<br>через Trade');});}
if((location.href).indexOf("steamcommunity.com")>0){$J('.supernav_container').append('<a class="menuitem combain_pillar" href="#">Pillar</a>');$J('.combain_pillar').click(function(){'use strict';(function(){if(!location.href.match(/^https?:\/\/steamcommunity.com\/(?:id|profiles)\/[^\/]+\/badges\/2/)){location.href='//steamcommunity.com/my/badges/2';return;}
if(!g_steamID){alert('No logged on!');return;}
var k_ExpectedTasksCount=28;var g_SteamTasks=$J('.badge_task');if(g_SteamTasks.length!=k_ExpectedTasksCount){console.error('Expected tasks '+k_ExpectedTasksCount+', but found '+g_SteamTasks.length);console.error('Stopped');return;}
var g_TasksQueue=[];var bTaskBroadcast=isTaskAvailable(3);var bTaskWorkshopRate=isTaskAvailable(11);var bTaskWorkshopSubscribe=isTaskAvailable(12);var bTaskWorkshop=bTaskWorkshopRate||bTaskWorkshopSubscribe;var bTaskCommunityProfileRealName=isTaskAvailable(16);var bTaskCommunityProfile=bTaskCommunityProfileRealName||isTaskAvailable(15)||isTaskAvailable(17);var bTaskJoinGroup=isTaskAvailable(18);var bTaskProfileComment=isTaskAvailable(19);var bTaskFeedRateUp=isTaskAvailable(20);var bTaskPostStatus=isTaskAvailable(21);var bTaskSelectBadge=isTaskAvailable(24);var bTaskDiscussionsSearch=isTaskAvailable(26);function isTaskAvailable(task_id){var task=g_SteamTasks.eq(task_id);if(!task.length)
return false;return task.find('.quest_icon').attr('src').indexOf('_off')!=-1;}
function DoTaskBroadcast(next){$J.get('//steamcommunity.com/apps/allcontenthome?appHubSubSection=13').done(function(data){var match=data.match(/watch\/(\d+)/);if(!match){console.error('[DoTaskBroadcast] Fail! (2)');return next();}
$J.get('//steamcommunity.com/broadcast/getbroadcastmpd/?steamid='+match[1]+'&broadcastid=0&viewertoken=0').done(function(data){if(data.success!=='ready'){console.error('[DoTaskBroadcast] Fail! (4)');}else{console.log('[DoTaskBroadcast] OK!');}}).fail(function(){console.error('[DoTaskBroadcast] Fail! (3)');}).always(function(){next();});}).fail(function(){console.error('[DoTaskBroadcast] Fail! (1)');next();});}
function DoTaskWorkshop(next){$J.get('//steamcommunity.com/workshop/browse/',{appid:440,browsesort:'totaluniquesubscribers'}).done(function(data){var matches=data.match(/sharedfile_(\d+)/g);if(!matches){console.error('[DoTaskWorkshop] Fail! (2)');return next();}
var file_id=matches[Math.floor(Math.random()*matches.length)].substr(11);var isDone=false;if(bTaskWorkshopRate){console.log('[DoTaskWorkshop] Upvoting id#'+file_id);$J.post('//steamcommunity.com/sharedfiles/voteup',{id:file_id,sessionid:g_sessionID}).done(function(data){if(data.success==1){console.log('[DoTaskWorkshop] Rate - OK!');}else{console.error('[DoTaskWorkshop] Rate - Fail! (4)');}}).fail(function(){console.error('[DoTaskWorkshop] Rate - Fail! (3)');}).always(function(){if(!bTaskWorkshopSubscribe||isDone){return next();}
isDone=true;});}
if(bTaskWorkshopSubscribe){console.log('[DoTaskWorkshop] Subscribing id#'+file_id);$J.post('//steamcommunity.com/sharedfiles/subscribe',{id:file_id,appid:440,sessionid:g_sessionID}).done(function(data){if(data.success==1){console.log('[DoTaskWorkshop] Subscribe - OK!');$J.post('//steamcommunity.com/sharedfiles/unsubscribe',{id:file_id,appid:440,sessionid:g_sessionID}).done(function(data){if(data.success==1){console.log('[DoTaskWorkshop] Unsubscribed');}});}else{console.error('[DoTaskWorkshop] Subscribe - Fail! (4)');}}).fail(function(){console.error('[DoTaskWorkshop] Subscribe - Fail! (3)');}).always(function(){if(!bTaskWorkshopRate||isDone){return next();}
isDone=true;});}}).fail(function(){console.error('[DoTaskWorkshop] Fail! (1)');next();});}
function DoTaskCommunityProfile(next){$J.get('//steamcommunity.com/profiles/'+g_steamID+'/edit').done(function(data){var form=$J(data).find('form').eq(0);if(bTaskCommunityProfileRealName){form.find('#real_name').val(form.find('#personaName').val())}
$J.post('//steamcommunity.com/profiles/'+g_steamID+'/edit',form.serialize()).done(function(data){console.log('[DoTaskCommunityProfile] OK!');}).fail(function(){console.error('[DoTaskCommunityProfile] Fail! (2)');}).always(function(){next();});}).fail(function(){console.error('[DoTaskCommunityProfile] Fail! (1)');next();});}
function DoTaskJoinGroup(next){$J.post('//steamcommunity.com/groups/tradingcards',{action:'join',sessionID:g_sessionID}).done(function(){console.log('[DoTaskJoinGroup] OK!');}).fail(function(){console.error('[DoTaskJoinGroup] Fail!');}).always(function(){next();});}
function DoTaskProfileComment(next){$J.post('//steamcommunity.com/comment/Profile/post/'+g_steamID+'/-1/',{comment:':steammocking:',count:0,sessionid:g_sessionID}).done(function(data){if(data.success){console.log('[DoTaskProfileComment] OK!');}else{console.error('[DoTaskProfileComment] Fail! (2)');}}).fail(function(){console.error('[DoTaskProfileComment] Fail! (1)');}).always(function(){next();});}
function DoTaskFeedRateUp(next){$J.post('//steamcommunity.com/actions/LogFriendActivityUpvote',{sessionID:g_sessionID}).done(function(){console.log('[DoTaskFeedRateUp] OK!');}).fail(function(){console.error('[DoTaskFeedRateUp] Fail!');}).always(function(){next();});}
function DoTaskPostStatus(next){$J.post('//steamcommunity.com/profiles/'+g_steamID+'/ajaxpostuserstatus/',{sessionid:g_sessionID,status_text:'Hello World!',appid:0}).done(function(data){if(data.success&&data.blotter_html){console.log('[DoTaskPostStatus] OK!');var postid=data.blotter_html.match(/userstatus_(\d+)_/)[1];$J.post('//steamcommunity.com/profiles/'+g_steamID+'/ajaxdeleteuserstatus/',{sessionid:g_sessionID,postid:postid}).done(function(data){if(data.success){console.log('[DoTaskPostStatus] Post removed');}});}else{console.error('[DoTaskPostStatus] Fail! (2)');}}).fail(function(){console.error('[DoTaskPostStatus] Fail! (1)');}).always(function(){next();});}
function DoTaskSelectBadge(next){$J.post('//steamcommunity.com/profiles/'+g_steamID+'/badges/2',{action:'setfavoritebadge',sessionid:g_sessionID,badgeid:2}).done(function(data){if(data.indexOf('class="profile_fatalerror"')!=-1){console.error('[DoTaskSelectBadge] Fail! (2)');}else{console.log('[DoTaskSelectBadge] OK!');}}).fail(function(){console.error('[DoTaskSelectBadge] Fail! (1)');}).always(function(){next();});}
function DoTaskDiscussionsSearch(next){$J.ajax({url:'//steamcommunity.com/discussions/forum/  search/?gidforum=882958665520871138&q=%57%68%65%72%65%20%69%73%20%48%61%6C%66%2D%4C%69%66%65%20%33%3F',type:'HEAD'}).done(function(){console.log('[DoTaskDiscussionsSearch] OK!');}).fail(function(){console.error('[DoTaskDiscussionsSearch] Fail!');}).always(function(){next();});}
function DoNextTask(){var Task=g_TasksQueue.shift();if(Task){Task(DoNextTask);}else{console.log('Done! Refresh the page and see what happened');location.reload();}};if(bTaskBroadcast){g_TasksQueue.push(DoTaskBroadcast);console.log('Added task `Broadcast`');}
if(bTaskWorkshop){g_TasksQueue.push(DoTaskWorkshop);console.log('Added task `Workshop`');}
if(bTaskCommunityProfile){g_TasksQueue.push(DoTaskCommunityProfile);console.log('Added task `CommunityProfile`');}
if(bTaskJoinGroup){g_TasksQueue.push(DoTaskJoinGroup);console.log('Added task `JoinGroup`');}
if(bTaskProfileComment){g_TasksQueue.push(DoTaskProfileComment);console.log('Added task `ProfileComment`');}
if(bTaskFeedRateUp){g_TasksQueue.push(DoTaskFeedRateUp);console.log('Added task `FeedRateUp`');}
if(bTaskPostStatus){g_TasksQueue.push(DoTaskPostStatus);console.log('Added task `PostStatus`');}
if(bTaskDiscussionsSearch){g_TasksQueue.push(DoTaskDiscussionsSearch);console.log('Added task `DiscussionsSearch`');}
if(bTaskSelectBadge){g_TasksQueue.push(DoTaskSelectBadge);console.log('Added task `SelectBadge`');}
if(!g_TasksQueue.length){console.log('Nothing to do. Great job! :)');return;}
DoNextTask();})();});}